<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><UserSecretsId>sdv-next-api</UserSecretsId></PropertyGroup><ItemGroup><PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" /><PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3" /></ItemGroup><ItemGroup><ProjectReference Include="..\SDV.Application\SDV.Application.csproj" /><ProjectReference Include="..\SDV.Contracts\SDV.Contracts.csproj" /><ProjectReference Include="..\SDV.Infrastructure\SDV.Infrastructure.csproj" /></ItemGroup></Project>
